meiduo_mall/meiduo_mall/apps/areas/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # 省市区三级联动
    url(r'^areas/$', views.AreasView.as_view()),
]

meiduo_mall/meiduo_mall/apps/carts/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # 购物车管理
    url(r'^carts/$', views.CartsView.as_view(), name='info'),
    # 全选gwc
    url(r'carts/selection/', views.CartsSelectAllView.as_view()),
]

meiduo_mall/meiduo_mall/apps/demo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login_with_cookie/$', views.login_with_cookie, name='login_with_cookie'),
    url(r'^login_with_session/$', views.login_with_session, name='login_with_session'),
    url(r'^recursion/$', views.recursion, name='recursion'),
]

meiduo_mall/meiduo_mall/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # haystack
    url(r'^search/', include('haystack.urls')),
    # demo
    url(r'^demo/', include('demo.urls')),
    # users
    url(r'^', include('users.urls', namespace='users')),
    # contents
    url(r'^', include('contents.urls', namespace='contents')),
    # verifications
    url(r'^', include('verifications.urls')),
    # oauth
    url(r'^', include('oauth.urls')),
    # areas
    url(r'^', include('areas.urls')),
    # goods
    url(r'^', include('goods.urls', namespace='goods')),
    # carts
    url(r'^', include('carts.urls', namespace='carts')),
    # order
    url(r'^', include('orders.urls', namespace='orders')),
    # payment
    url(r'^', include('payment.urls', namespace='payment')),
]

meiduo_mall/meiduo_mall/apps/goods/models.py
from django.db import models

from meiduo_mall.utils.models import BaseModel


class GoodsCategory(BaseModel):
    """商品类别"""
    name = models.CharField(max_length=10, verbose_name='名称')
    parent = models.ForeignKey('self', related_name='subs', null=True, blank=True, on_delete=models.CASCADE,
                               verbose_name='父类别')

    class Meta:
        db_table = 'tb_goods_category'
        verbose_name = '商品类别'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_hot_skus(self):
        # 面向对象
        return self.sku_set.filter(is_launched=True).order_by('-sales')[:2]


class GoodsChannelGroup(BaseModel):
    """商品频道组"""
    name = models.CharField(max_length=20, verbose_name='频道组名')

    class Meta:
        db_table = 'tb_channel_group'
        verbose_name = '商品频道组'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannel(BaseModel):
    """商品频道"""
    group = models.ForeignKey(GoodsChannelGroup, verbose_name='频道组名')
    category = models.ForeignKey(GoodsCategory, unique=True, on_delete=models.CASCADE, verbose_name='顶级商品类别')
    url = models.CharField(max_length=50, verbose_name='频道页面链接')
    sequence = models.IntegerField(verbose_name='组内顺序')

    class Meta:
        db_table = 'tb_goods_channel'
        verbose_name = '商品频道'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.category.name


class Brand(BaseModel):
    """品牌"""
    name = models.CharField(max_length=20, verbose_name='名称')
    logo = models.ImageField(verbose_name='Logo图片')
    first_letter = models.CharField(max_length=1, verbose_name='品牌首字母')

    class Meta:
        db_table = 'tb_brand'
        verbose_name = '品牌'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SPU(BaseModel):
    """商品SPU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, verbose_name='品牌')
    category1 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat1_spu', verbose_name='一级类别')
    category2 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat2_spu', verbose_name='二级类别')
    category3 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat3_spu', verbose_name='三级类别')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    desc_detail = models.TextField(default='', verbose_name='详细介绍')
    desc_pack = models.TextField(default='', verbose_name='包装信息')
    desc_service = models.TextField(default='', verbose_name='售后服务')

    class Meta:
        db_table = 'tb_spu'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SKU(BaseModel):
    """商品SKU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    caption = models.CharField(max_length=100, verbose_name='副标题')
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, verbose_name='商品')
    category = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, verbose_name='从属类别')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='单价')
    cost_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='进价')
    market_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='市场价')
    stock = models.IntegerField(default=0, verbose_name='库存')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    is_launched = models.BooleanField(default=True, verbose_name='是否上架销售')
    default_image = models.ImageField(max_length=200, default='', null=True, blank=True, verbose_name='默认图片')

    class Meta:
        db_table = 'tb_sku'
        verbose_name = '商品SKU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.id, self.name)


class SKUImage(BaseModel):
    """SKU图片"""
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE, verbose_name='sku')
    image = models.ImageField(verbose_name='图片')

    class Meta:
        db_table = 'tb_sku_image'
        verbose_name = 'SKU图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.sku.name, self.id)


class SPUSpecification(BaseModel):
    """商品SPU规格"""
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, related_name='specs', verbose_name='商品SPU')
    name = models.CharField(max_length=20, verbose_name='规格名称')

    class Meta:
        db_table = 'tb_spu_specification'
        verbose_name = '商品SPU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.spu.name, self.name)


class SpecificationOption(BaseModel):
    """规格选项"""
    spec = models.ForeignKey(SPUSpecification, related_name='options', on_delete=models.CASCADE, verbose_name='规格')
    value = models.CharField(max_length=20, verbose_name='选项值')

    class Meta:
        db_table = 'tb_specification_option'
        verbose_name = '规格选项'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s - %s' % (self.spec, self.value)


class SKUSpecification(BaseModel):
    """SKU具体规格"""
    sku = models.ForeignKey(SKU, related_name='specs', on_delete=models.CASCADE, verbose_name='sku')
    spec = models.ForeignKey(SPUSpecification, on_delete=models.PROTECT, verbose_name='规格名称')
    option = models.ForeignKey(SpecificationOption, on_delete=models.PROTECT, verbose_name='规格值')

    class Meta:
        db_table = 'tb_sku_specification'
        verbose_name = 'SKU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s - %s' % (self.sku, self.spec.name, self.option.value)


class GoodsVisitCount(BaseModel):
    """统计分类商品访问量模型类"""
    category = models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='商品分类')
    count = models.IntegerField(verbose_name='访问量', default=0)
    date = models.DateField(auto_now_add=True, verbose_name='统计日期')

    class Meta:
        db_table = 'tb_goods_visit'
        verbose_name = '统计分类商品访问量'
        verbose_name_plural = verbose_name
        unique_together = (('date', 'category'),)

meiduo_mall/meiduo_mall/apps/areas/views.py
from django.shortcuts import render
from django.views import View
from django import http
import logging
from django.core.cache import cache

from areas.models import Area
from meiduo_mall.utils.response_code import RETCODE

logger = logging.getLogger('django')


class AreasView(View):
    """省市区三级联动"""

    def get(self, request):
        # 判断当前是要查询省份数据还是市区数据
        area_id = request.GET.get('area_id')

        if not area_id:
            # 获取并判断是否有缓存
            province_list = cache.get('province_list')

            if not province_list:
                # 查询省级数据
                try:
                    province_model_list = Area.objects.filter(parent__isnull=True)

                    # 需要将模型列表转成字典列表
                    province_list = []
                    for province_model in province_model_list:
                        province_dict = {
                            "id": province_model.id,
                            "name": province_model.name
                        }
                        province_list.append(province_dict)

                    # 缓存省份字典列表数据:默认存储到别名为"default"的配置中
                    cache.set('province_list', province_list, 3600)
                except Exception as e:
                    logger.error(e)
                    return http.JsonResponse({'code': RETCODE.DBERR, 'errmsg': '查询省份数据错误'})

            # 响应省级JSON数据
            return http.JsonResponse({'code': RETCODE.OK, 'errmsg': 'OK', 'province_list': province_list})
        else:
            # 判断是否有缓存
            sub_data = cache.get('sub_area_' + area_id)

            if not sub_data:
                # 查询城市或区县数据
                try:
                    parent_model = Area.objects.get(id=area_id)
                    # sub_model_list = parent_model.area_set.all()
                    sub_model_list = parent_model.subs.all()

                    # 将子级模型列表转成字典列表
                    subs = []
                    for sub_model in sub_model_list:
                        sub_dict = {
                            "id": sub_model.id,
                            "name": sub_model.name
                        }
                        subs.append(sub_dict)

                    # 构造子级JSON数据
                    sub_data = {
                        'id': parent_model.id,
                        'name': parent_model.name,
                        'subs': subs
                    }

                    # 缓存城市或者区县
                    cache.set('sub_area_' + area_id, sub_data, 3600)
                except Exception as e:
                    logger.error(e)
                    return http.JsonResponse({'code': RETCODE.DBERR, 'errmsg': '查询城市或区县数据错误'})

            # 响应城市或区县JSON数据
            return http.JsonResponse({'code': RETCODE.OK, 'errmsg': 'OK', 'sub_data': sub_data})

meiduo_mall/meiduo_mall/apps/contents/views.py
from django.shortcuts import render
from django.views import View
from collections import OrderedDict

from goods.models import GoodsChannelGroup, GoodsChannel, GoodsCategory
from contents.models import ContentCategory, Content


# Create your views here.


class IndexView(View):
    """首页广告"""

    def get(self, request):
        """提供首页广告页面"""
        # 查询并展示商品分类
        # 准备商品分类对应的字典
        categories = OrderedDict()    #  {}
        # 查询所有的商品频道:37个一级类别
        channels = GoodsChannel.objects.order_by('group_id', 'sequence')
        # 遍历所有频道
        for channel in channels:  #  100手机（1）  101相机（1）  102电脑（2）
            # 获取当前频道所在的组
            group_id = channel.group_id    # 2
            # 构造基本的数据框架:只有11个组
            if group_id not in categories:
                categories[group_id] = {'channels': [], 'sub_cats': []}
                # { '1': {'channels': [], 'sub_cats': [] }

            # 查询当前频道对应的一级类别
            cat1 = channel.category
            # 将cat1添加到channels
            categories[group_id]['channels'].append({
                'id': cat1.id,
                'name': cat1.name,
                'url': channel.url
            })
            #
            # { '1': {'channels': [ { 'id': 100, 'name': '手机','url': url}
            #  ， 'id': 101, 'name': '相机','url': url}  ],
            #  'sub_cats': []
            #   '2' : {'channels': [  { 'id': 102, 'name': '电脑','url': url} ], 'sub_cats': []}
            # }

            # 查询二级和三级类别
            for cat2 in cat1.subs.all():  # 从一级类别找二级类别
                cat2.sub_cats = []  # 给二级类别添加一个保存三级类别的列表
                for cat3 in cat2.subs.all():  # 从二级类别找三级类别
                    cat2.sub_cats.append(cat3)  # 将三级类别添加到二级sub_cats

                # 将二级类别添加到一级类别的sub_cats
                categories[group_id]['sub_cats'].append(cat2)

        # 查询首页广告数据
        # 查询所有的广告类别
        contents = OrderedDict()
        content_categories = ContentCategory.objects.all()
        for content_category in content_categories:
            # 使用广告类别查询出该类别对应的所有的广告内容
            contents[content_category.key] = content_category.content_set.filter(
                status=True).order_by('sequence')  # 查询出未下架的广告并排序
            # 链式查询  QuerySet.filter()    QuerySet

        # 构造上下文
        # from contents.utils import get_categories
        # categories = get_categories()
        context = {
            'categories': categories,
            'contents': contents
        }

        return render(request, 'index.html', context)

meiduo_mall/meiduo_mall/apps/demo/views.py
from django import http
from django.shortcuts import render, redirect

from goods.models import GoodsCategory


def login_with_cookie(request):
    if request.method == 'GET':
        uid = request.COOKIES.get('uid')
        if not uid:
            return render(request, 'demo/login.html')
        else:
            return render(request, 'demo/home.html', {'uid': uid})
    else:
        uid = request.POST.get('uid')
        response = redirect('login_with_cookie')
        response.set_cookie('uid', uid)
        return response


def login_with_session(request):
    if request.method == 'GET':
        uid = request.session.get('uid')
        if not uid:
            return render(request, 'demo/login.html')
        else:
            return render(request, 'demo/home.html', {'uid': uid})
    else:
        uid = request.POST.get('uid')
        request.session['uid'] = uid
        return redirect('login_with_session')


def recursion(request):
    cat1_list = GoodsCategory.objects.filter(parent__isnull=True)
    return render(request, 'demo/recursion.html', {'cat1_list': cat1_list})

meiduo_mall/meiduo_mall/apps/verifications/views.py
from django.shortcuts import render
from django.views import View
from django_redis import get_redis_connection
from django import http
import random, logging

from verifications.libs.captcha.captcha import captcha
from . import constants
from meiduo_mall.utils.response_code import RETCODE
from verifications.libs.yuntongxun.ccp_sms import CCP
from celery_tasks.sms.tasks import send_sms_code

# 创建日志输出器
logger = logging.getLogger('django')


class SMSCodeView(View):
    """短信验证码"""

    def get(self, request, mobile):
        """
        :param mobile: 手机号
        :return: JSON
        """
        # 接受参数
        image_code_client = request.GET.get('image_code')
        uuid = request.GET.get('uuid')

        # 校验参数
        if not all([image_code_client, uuid]):
            return http.HttpResponseForbidden('缺少必传参数')

        # 提取图形验证码
        redis_conn = get_redis_connection('verify_code')
        # 判断用户是否频繁发送短信验证码
        send_flag = redis_conn.get('send_flag_%s' % mobile)
        if send_flag:
            return http.JsonResponse({'code': RETCODE.THROTTLINGERR, 'errmsg': '发送短信过于频繁'})

        image_code_server = redis_conn.get('img_%s' % uuid)
        if image_code_server is None:
            return http.JsonResponse({'code': RETCODE.IMAGECODEERR, 'errmsg': '图形验证码已失效'})
        # 删除图形验证码
        redis_conn.delete('img_%s' % uuid)
        # 对比图形验证码
        image_code_server = image_code_server.decode()  # 将bytes转字符串，再比较
        if image_code_client.lower() != image_code_server.lower():  # 转小写，再比较
            return http.JsonResponse({'code': RETCODE.IMAGECODEERR, 'errmsg': '输入图形验证码有误'})

        # 生成短信验证码：随机6位数字，000007
        sms_code = '%06d' % random.randint(0, 999999)
        logger.info(f'给 {mobile} 发送注册手机验证码 {sms_code} ')  # 手动的输出日志，记录短信验证码
        # 创建redis管道
        pl = redis_conn.pipeline()
        # 将命令添加到队列中
        # 保存短信验证码
        pl.setex('sms_%s' % mobile, constants.SMS_CODE_REDIS_EXPIRES, sms_code)
        # 保存发送短信验证码的标记
        pl.setex('send_flag_%s' % mobile, constants.SEND_SMS_CODE_INTERVAL, 1)
        # 执行
        pl.execute()

        # # 发送短信验证码
        # from django.conf import settings
        # if not settings.DEBUG:
        #     CCP().send_template_sms(mobile, [sms_code, constants.SMS_CODE_REDIS_EXPIRES // 60],
        #                             constants.SEND_SMS_TEMPLATE_ID)
        from django.conf import settings
        if not settings.DEBUG:
            # 使用Celery发送短信验证码
            # send_sms_code(mobile, sms_code)  # 错误的写法
            send_sms_code.delay(mobile, sms_code)  # 千万不要忘记写delay

        # 响应结果
        return http.JsonResponse({'code': RETCODE.OK, 'errmsg': '发送短信成功'})


class ImageCodeView(View):
    """图形验证码"""

    def get(self, request, uuid):
        """
        :param uuid: 通用唯一识别码，用于唯一标识该图形验证码属于哪个用户的
        :return: image/jpg
        """
        # 实现主体业务逻辑：生成，保存，响应图形验证码
        # 生成图形验证码
        text, image = captcha.generate_captcha()

        # 保存图形验证码
        redis_conn = get_redis_connection('verify_code')
        # redis_conn.setex('key', 'expires', 'value')
        redis_conn.setex('img_%s' % uuid, constants.IMAGE_CODE_REDIS_EXPIRES, text)

        # 响应图形验证码
        return http.HttpResponse(image, content_type='image/jpg')

meiduo_mall/meiduo_mall/templates/list.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>美多商城-商品列表</title>
    <link rel="stylesheet" type="text/css" href="{{ static('css/jquery.pagination.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ static('css/reset.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ static('css/main.css') }}">
    <script type="text/javascript" src="{{ static('js/jquery-1.12.4.min.js') }}"></script>
	<script type="text/javascript" src="{{ static('js/vue-2.5.16.js') }}"></script>
    <script type="text/javascript" src="{{ static('js/axios-0.18.0.min.js') }}"></script>
</head>
<body>
	<div id="app">
	<div class="header_con">
		<div class="header" v-cloak>
			<div class="welcome fl">欢迎来到美多商城!</div>
			<div class="fr">
                <div v-if="username" class="login_btn fl">
                    欢迎您：<em>[[ username ]]</em>
                    <span>|</span>
                    <a href="{{ url('users:logout') }}">退出</a>
                </div>
                <div v-else class="login_btn fl">
                    <a href="{{ url('users:login') }}">登录</a>
                    <span>|</span>
                    <a href="{{ url('users:register') }}">注册</a>
                </div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{{ url('users:info') }}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>
	<div class="search_bar clearfix">
		<a href="{{ url('contents:index') }}" class="logo fl"><img src="{{ static('images/logo.png') }}"></a>
		<div class="search_wrap fl">
			<form method="get" action="/search/" class="search_con">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
			<ul class="search_suggest fl">
				<li><a href="#">索尼微单</a></li>
				<li><a href="#">优惠15元</a></li>
				<li><a href="#">美妆个护</a></li>
				<li><a href="#">买2免1</a></li>
			</ul>
		</div>
		<div class="guest_cart fr">
			<a href="cart.html" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">2</div>
			<ul class="cart_goods_show">
				<li>
					<img src="{{ static('images/goods/goods001.jpg') }}" alt="商品图片">
					<h4>华为 HUAWEI P10 Plus 6GB+64GB 钻雕金 移动联通电信4G手机 双卡双待</h4>
					<div>1</div>
				</li>
				<li>
					<img src="{{ static('images/goods/goods002.jpg') }}" alt="商品图片">
					<h4>Apple iPhoneX 64GB 深空灰色 移动联通电信4G手机</h4>
					<div>1</div>
				</li>
			</ul>			
		</div>
	</div>
	<div class="navbar_con">
		<div class="navbar">
			<div class="sub_menu_con fl">
				<h1 class="fl">商品分类</h1>
				<ul class="sub_menu">
                    {% for group in categories.values() %}
                    <li>
                        <div class="level1">
                            {% for channel in group.channels %}
                            <a href="{{ channel.url }}">{{ channel.name }}</a>
                            {% endfor %}
                        </div>
                        <div class="level2">
                            {% for cat2 in group.sub_cats %}
                            <div class="list_group">
                                <div class="group_name fl">{{ cat2.name }} &gt;</div>
                                <div class="group_detail fl">
                                    {% for cat3 in cat2.sub_cats %}
                                    <a href="/list/{{ cat3.id }}/1/">{{ cat3.name }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">真划算</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
	<div class="breadcrumb">
{#        {{ category.parent.parent.goodschannel_set.first().url }}#}
        {% if category  %}
            {# 至少有一级类别 #}
            {% if category.parent %}
                {# 至少有二级类别，当前查的可能是三级也可能是二级 #}
                {% if category.parent.parent %}
                    {# 至少一共有三级类别，当前查的是第三级 #}
                    <a href="javascript:;">{{ category.parent.parent.name }}</a>
                    <span>></span>
                 {% endif %}
                    <a href="javascript:;">{{ category.parent.name }}</a>
                <span>></span>
             {% endif %}
            <a href="javascript:;">{{ category.name }}</a>
        {% endif %}
{#		<a href="http://shouji.jd.com/">{{ breadcrumb.cat1.name }}</a>#}
{#		<span>></span>#}
{#		<a href="javascript:;">{{ breadcrumb.cat2.name }}</a>#}
{#        <span>></span>#}
{#		<a href="javascript:;">{{ breadcrumb.cat3.name }}</a>#}
	</div>
	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>热销排行</h3>
				<ul>
                    <li v-for="sku in hot_skus">
                        <a :href="sku.url"><img :src="sku.default_image_url"></a>
                        <h4><a :href="sku.url">[[ sku.name ]]</a></h4>
                        <div class="price">￥[[ sku.price ]]</div>
                    </li>
                </ul>
			</div>
		</div>
		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
                <a href="{{ url('goods:list', args=(category_id, 1)) }}?sort=default" {% if sort=='default' %}class="active"{% endif %}>默认</a>
                <a href="{{ url('goods:list', args=(category_id, 1)) }}?sort=price" {% if sort=='price' %}class="active"{% endif %}>价格</a>
                <a href="{{ url('goods:list', args=(category_id, 1)) }}?sort=hot" {% if sort=='hot' %}class="active"{% endif %}>人气</a>
{#				<a href="/list/115/1/?sort=default" class="active">默认</a>#}
{#				<a href="/list/115/1/?sort=price">价格</a>#}
{#				<a href="/list/115/1/?sort=hot">人气</a>#}
			</div>
			<ul class="goods_type_list clearfix">
                {% for sku in page_skus %}
                    <li>
                        <a href="detail.html"><img src="{{ sku.default_image.url }}"></a>
                        <h4><a href="detail.html">{{ sku.name }}</a></h4>
                        <div class="operate">
                            <span class="price">￥{{ sku.price }}</span>
                            <span class="unit">台</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
			</ul>
            {# 前端分页器插件内容 #}
            <div class="pagenation">
                <div id="pagination" class="page"></div>
            </div>
		</div>
	</div>
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	</div>
	<script type="text/javascript">
        let category_id = "{{ category_id }}";
    </script>
	<script type="text/javascript" src="{{ static('js/common.js') }}"></script>
	<script type="text/javascript" src="{{ static('js/list.js') }}"></script>
	<script type="text/javascript" src="{{ static('js/jquery.pagination.min.js') }}"></script>
	<script>
        $(function () {
            $('#pagination').pagination({
                currentPage: {{ page_num }}, // 当期所在页码
                totalPage: {{ total_page }},   // 总页数
                callback:function (current) {
                    {#location.href = '/list/115/1/?sort=default';#}
                    location.href = '/list/{{ category_id }}/' + current + '/?sort={{ sort }}';
                }
            })
        });
    </script>
</body>
</html>